/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_zjucst_jni_ZKVotingJNI */

#ifndef _Included_cn_edu_zjucst_jni_ZKVotingJNI
#define _Included_cn_edu_zjucst_jni_ZKVotingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_zjucst_jni_ZKVotingJNI
 * Method:    generateVoterKeys
 * Signature: (I)Lcn/edu/zjucst/jni/Key;
 */
JNIEXPORT jobject JNICALL Java_cn_edu_zjucst_jni_ZKVotingJNI_generateVoterKeys
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_edu_zjucst_jni_ZKVotingJNI
 * Method:    verifyVoterProof
 * Signature: (Lcn/edu/zjucst/jni/Proof;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_edu_zjucst_jni_ZKVotingJNI_verifyVoterProof
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
